[profile.default]
solc_version = '0.7.6'
libs = ['lib']
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
]
optimizer=true
optimizer_runs=999999999
sizes = true
via_ir = false
gas_reports = ['*']
gas_reports_ignore = []

[profile.default.rpc_endpoints]
# todo put these into a secrets file
arbitrum_alchemy='https://arb-mainnet.g.alchemy.com/v2/L0eaUwWEoWzszCK9EhqHdl_p7VHStkaC'
arbitrum_ankr='https://rpc.ankr.com/arbitrum/056ed471570655a3bb77cf31b9e3576658d63d2acb88911f84e7acaf211b55ac'
arbitrum_publicnode='https://arbitrum-one.publicnode.com'
